services:
    mariadb:
        build: ./requirements/mariadb
        image: mariadb:1.0
        container_name: mariadb
        restart: always
        env_file:
            - .env
        volumes:
            - mariadb_vol:/var/lib/mysql
        networks:
            - hiver
    nginx:
        build: ./requirements/nginx
        image: nginx:1.0
        container_name: nginx
        restart: always
        depends_on:
            - wordpress
        ports:
            - "8443:443"
        networks:
            - hiver
    wordpress:
        build: ./requirements/wordpress
        image: wordpress:1.0
        container_name: wordpress
        restart: always
        env_file:
            - .env
        depends_on:
            - mariadb
        volumes:
            - wp_vol:/var/www/wordpress
        networks:
            - hiver

volumes:
    mariadb_vol:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/mariadb
    wp_vol:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${HOME}/data/wp

networks:
    hiver:
        driver: bridge
