services:
# mariadb:
#     build: ./requirements/mariadb
#     container_name: mariadb
#     restart: always
#     env_file:
#         - .env
#     volumes:
#         - db_vol:/var/lib/mysql
#     ports:
#         - "3306:3306"
#     networks:
#         - inception_network
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        restart: always
        depends_on:
            - wordpress
        ports:
            - "8443:443"
        networks:
            - inception_network

    wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        restart: always
        volumes:
            - wp_files_vol:/var/www/wordpress
        ports:
            - "9000"
        networks:
            - inception_network

volumes:
    db_vol:
    wp_files_vol:

networks:
    inception_network:
        driver: bridge
